Bump OpenBSD to 6.9 and install full sets
cross-platform-actions/openbsd-builder pull request #2
Opened 2021-09-01 01:25 UTC by ZhanYF

Please see #1  for more info. 

P.S. https://github.com/cross-platform-actions/action has to be tweaked to use the new version.

2021-09-01 05:22 UTC, jacob-carlborg requested changes

2021-09-01 05:22 UTC, jacob-carlborg commented on .github/workflows/build.yml
> +            - 6.9
Don't change this value, add a new entry.

2021-09-01 05:22 UTC, jacob-carlborg commented on resources/install.conf
> -Set name(s) = -game* -x* -man*
Please move this and related changes to a separate PR, as discussed in the issue.

2021-09-03 01:35 UTC, ZhanYF commented
Closing since we had #4

2021-09-03 01:35 UTC, closed without merging